### ISSUE TITLE
暂不提供可视化界面，请直接使用脚本进行请求。

### ISSUE THREAD

**Issue by dengliming** [duolabmeng6/paddlehub_ppocr#14]
部署完之后请求报这个错。
`暂不提供可视化界面，请直接使用脚本进行请求。<br/>No visual interface is provided for the time being, please use the python script to make a request directly.`

**Comment by duolabmeng6** [comment]
已经成功啦啊 脚本请求就可以了

**Comment by dengliming** [comment]
脚本怎么操作？不能通过函数url来测？

**Comment by dengliming** [comment]
没带后缀。/predict/ocr_system

**Comment by duolabmeng6** [comment]
你今天构建这个脚本用的是什么版本呢？我今天正好构件了一下失败了。21年的东西是有点久远

**Comment by dengliming** [comment]
我还没试新版本的，只是拿你之前上传到docker hub上的，拉下来部署一下，发现准确率还是比现在官方的低很多。有空可以继续研究下

**Comment by duolabmeng6** [comment]
这个21年的模型啦 第二代的飞桨ocr模型  大佬留个地址给我...我都构建不起来了 哈哈哈哈哈哈 飞桨把库都删了那个版本..哈哈哈
也可以构建个新版本
精确度跟模型有关系的 服务端版本是大的模型精确度才高 默认是小模型速度快适合函数计算

**Comment by dengliming** [comment]
我是参考这个测试的
https://registry.hub.docker.com/r/duolabmeng666/paddlehub_ppocr

docker pull duolabmeng666/paddlehub_ppocr:1.2
