### ISSUE TITLE
建议可以增加一部分前端的代码

### ISSUE THREAD

**Issue by langren1353** [duolabmeng6/paddlehub_ppocr#2]
建议可以增加一些前端的代码，方便直接开箱即用，这样使用的人会更多一些
参照用例：https://github.com/alisen39/TrWebOCR/fontend

**Comment by duolabmeng6** [comment]
收到 已经增加了前端页面了

**Comment by duolabmeng6** [comment]
[Serverless 应用中心一键体验 PaddleOCR](https://fcnext.console.aliyun.com/applications/create?template=PaddleOCR)

<img width="998" alt="image" src="https://user-images.githubusercontent.com/59047063/164473120-40b9c630-0cd6-4a62-ac19-3a7cf89638d0.png">
