### ISSUE TITLE
感谢大佬分享，问几个小白问题

### ISSUE THREAD

**Issue by fangch2004** [duolabmeng6/paddlehub_ppocr#7]
1 按我理解这个是只能通过restful调固定的模型跑 不支持自定义数据集进行训练对吧
2 如果识别速度/精度都有需求 速度大概到几十ms级的样子 图片已经压缩过了，这种情况下模型大吃cpu速度慢，模型小精度上不去，大佬能否指点下优化思路

**Comment by duolabmeng6** [comment]
看飞桨官网的教程
